---
title: "inst490-data-cleaning"
output: html_document
date: "2023-03-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#Import libraries and data
```{r}
library(tidyverse)
library(janitor)
library(googlesheets4)

NC <- read_sheet("https://docs.google.com/spreadsheets/d/15e1yxUzol0nLw96nG-cHQPPsPV5OpkD3AP0iprFP7lU/edit#gid=96980819", sheet="NC")

SS <- read_sheet("https://docs.google.com/spreadsheets/d/15e1yxUzol0nLw96nG-cHQPPsPV5OpkD3AP0iprFP7lU/edit#gid=96980819", sheet="SS")
```

#calculate percentage of missed trips
```{r}
NC_total <- nrow(NC)
SS_total <- nrow(SS)


NC_route_counts <- NC %>% 
  group_by(Route) %>%
  summarise(count=n()) %>%
  mutate(percentage = count/NC_total*100) %>%
  arrange(desc(percentage))


SS_route_counts <- SS %>%
  group_by(Route) %>%
  summarise(count=n()) %>%
  mutate(percentage = count/NC_total*100) %>%
  arrange(desc(percentage))

```

```{r}
sheet_write(NC_route_counts, ss="https://docs.google.com/spreadsheets/d/15e1yxUzol0nLw96nG-cHQPPsPV5OpkD3AP0iprFP7lU/edit#gid=96980819", sheet="NC missed routes percentages")

sheet_write(SS_route_counts, ss="https://docs.google.com/spreadsheets/d/15e1yxUzol0nLw96nG-cHQPPsPV5OpkD3AP0iprFP7lU/edit#gid=96980819", sheet="SS missed routes percentages")
```




#Data cleaning
```{r}
###
#checking variables for groups
###


#definitely issues with the spelling of destination, need to confirm each one and make common amongst them, remove errors
dest <- NC %>%
  group_by(Dest) %>% #Module, Date, Runnum, Block, Dest
  summarise(count=n()) %>%
  arrange(desc(count))


#9 categories for this it appears
time_in_svc <- NC %>%
  group_by(Time_in_Svc) %>%
  summarise(count=n()) %>%
  arrange(desc(count))


NC %>%
  group_by(Runnum) %>% #EventType has 17ish options, MechProblem is written reasoning, missed is NULL 1 or 0, what does this mean?
  summarise(count=n()) %>%
  arrange(desc(count))
#Location event lists a bunch of different codes, what do these coorespond to?
```

#Create a day of the week column in R and group by date and Runnum
```{r}
NC %>%
  

```



```{r}
test <- NC %>%
  pivot_longer(cols = c(EventType))
```




#The Bus data
```{r}
the_bus <- read_sheet("https://docs.google.com/spreadsheets/d/1TfrhX6KGOgUqPyYE7ef3cA6a8PACdRpggG1OpDnva4k/edit#gid=0")
```


```{r}

route_missed_tripe <- the_bus %>% 
  group_by(route) %>%
  mutate(total_scheduled = sum(scheduled)) %>%
  mutate(total_missed = sum(missed)) %>%
  mutate(percentage_missed = total_missed/total_scheduled*100) %>%
  select(route, total_scheduled, total_missed, percentage_missed) %>%
  distinct()
  
sheet_write(route_missed_tripe, ss="https://docs.google.com/spreadsheets/d/1TfrhX6KGOgUqPyYE7ef3cA6a8PACdRpggG1OpDnva4k/edit#gid=0", sheet="missed_trips_by_route")

```


```{r}
route_missed_trips_other <- the_bus %>% 
  group_by(route) %>%
  mutate(percentage_missed = mean(missed_of_scheduled))
```

```{r}
route_missed_tripe <- the_bus %>% 
  group_by(route) %>%
  mutate(total_scheduled = sum(scheduled)) %>%
  mutate(total_missed = sum(missed)) %>%
  mutate(percentage_missed = total_missed/total_scheduled*100) %>%
  select(route, total_scheduled, total_missed, percentage_missed) %>%
  distinct()

```






