---
title: "RideOn Cleaning - Gb and Gf"
author: "Devon Milley"
date: "2023-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Libraries
```{r}
library(readxl)
library(writexl)
library(tidyverse)
library(janitor)
library(dplyr)
library(googlesheets4)

```
#Cleaning
```{r}
#read in file
rideon_gf <- read_sheet("https://docs.google.com/spreadsheets/d/15e1yxUzol0nLw96nG-cHQPPsPV5OpkD3AP0iprFP7lU/edit#gid=96980819", sheet = "GF") %>% 
  mutate(
    Time_in_Svc = ""
  ) %>% 
  relocate(
    Time_in_Svc, .before = EventType
  ) %>% 
  clean_names()

rideon_gb <- read_sheet("https://docs.google.com/spreadsheets/d/15e1yxUzol0nLw96nG-cHQPPsPV5OpkD3AP0iprFP7lU/edit#gid=96980819", sheet = "GB") %>% 
  clean_names()

#rideon_gb cleaning
rideon_gb_clean <- rideon_gb %>% 
  mutate(
    date = as.Date(date), #this isnt working
    runnum = as.numeric(runnum),
    block = as.numeric(block),
    route = as.numeric(route),
    dest = str_squish(dest)
  ) %>% 
  mutate(
    clean_dest = case_when(
      dest == "\'LF" ~ "LF",
      dest == "\'SE" ~ "SE",
      dest == "CCJ" ~ "CJ",
      dest == "gn" ~ "GN",
      dest == "kv" ~ "KV",
      dest == "Lakeforest" ~ "LF",
      dest == "Lf" ~ "LF",
      dest == "MC\'" ~ "MC",
      dest == "rw" ~ "RW",
      dest == "se" ~ "SE",
      dest == "tt" ~ "TT",
      TRUE ~ dest
    )
  ) %>% 
  relocate(clean_dest, .after = dest) %>% 
  mutate(
    dest_full = case_when(
      clean_dest == "GB" ~ "Gaithersburg", #might not need
      clean_dest == "NC" ~ "Nicholson Court/Kensington", #might not need
      clean_dest == "SS" ~ "Silver Spring", #might not need
      clean_dest == "GF" ~ "Gaithersburg Flash", #might not need
      clean_dest == "GN" ~ "Germantown",
      clean_dest == "MV" ~ "Montgomery Village",
      clean_dest == "WH" ~ "Wheaton",
      clean_dest == "GL" ~ "Glenmont",
      clean_dest == "SE" ~ "Shady Grove East",
      clean_dest == "SW" ~ "Shady Grove West",
      clean_dest == "LF" ~ "Lake Forest",
      clean_dest == "RR" ~ "Rockville",
      clean_dest == "HC" ~ "Holy Cross Hospital",
      clean_dest == "KV" ~ "King's View",
      clean_dest == "CJ" ~ "Clarksburh",
      clean_dest == "MC" ~ "Medical Center",
      clean_dest == "RW" ~ "Rockville West",
      clean_dest == "TE" ~ "Twin Brooke East",
      clean_dest == "RE" ~ "Rockville East",
      clean_dest == "QO" ~ "Quinn's Orchard"
    )
  ) %>% 
  relocate(dest_full, .after = clean_dest)  %>% 
  mutate(
    weekday_weekend = case_when(
      day_of_week == "Monday"| day_of_week == "Tuesday" | day_of_week == "Wednesday" | day_of_week == "Thursday" | day_of_week == "Friday" ~ "weekday",
      TRUE ~ "weekend"
    )
  )

#rideon_gb_clean %>% group_by(missed) %>% summarise(count = n()) #can't figure out how to get rid of single quotes

#ride on gf cleaning
rideon_gf_clean <- rideon_gf %>% 
  mutate(
    date = as.Date(date), #this isnt worknig
    runnum = as.numeric(runnum),
    block = as.numeric(block),
    route = as.numeric(route),
    dest = str_squish(dest)
  ) %>% 
  mutate(
    clean_dest = case_when(
      dest == "SS\'" ~ "SS",
      dest == "SSTc" ~ "SSTC",
      dest == "SSSTC" ~ "SSTC",
      TRUE ~ dest
    )
  ) %>% 
  relocate(
    clean_dest, .after = dest
  ) %>% 
  mutate(
    dest_full = case_when(
      clean_dest == "GB" ~ "Gaithersburg", #might not need
      clean_dest == "NC" ~ "Nicholson Court/Kensington", #might not need
      clean_dest == "SS" ~ "Silver Spring", #might not need
      clean_dest == "GF" ~ "Gaithersburg Flash", #might not need
      clean_dest == "GN" ~ "Germantown",
      clean_dest == "MV" ~ "Montgomery Village",
      clean_dest == "WH" ~ "Wheaton",
      clean_dest == "GL" ~ "Glenmont",
      clean_dest == "SE" ~ "Shady Grove East",
      clean_dest == "SW" ~ "Shady Grove West",
      clean_dest == "LF" ~ "Lake Forest",
      clean_dest == "RR" ~ "Rockville",
      clean_dest == "HC" ~ "Holy Cross Hospital",
      clean_dest == "KV" ~ "King's View",
      clean_dest == "CJ" ~ "Clarksburh",
      clean_dest == "MC" ~ "Medical Center",
      clean_dest == "RW" ~ "Rockville West",
      clean_dest == "TE" ~ "Twin Brooke East",
      clean_dest == "RE" ~ "Rockville East",
      clean_dest == "QO" ~ "Quinn's Orchard"
    )
  ) %>% 
  relocate(dest_full, .after = clean_dest) %>% 
  mutate(
    weekday_weekend = case_when(
      day_of_week == "Monday"| day_of_week == "Tuesday" | day_of_week == "Wednesday" | day_of_week == "Thursday" | day_of_week == "Friday" ~ "weekday",
      TRUE ~ "weekend"
    )
  )

rideon_gf_clean %>%  group_by(weekday_weekend) %>% summarise(count = n())


```

